import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-waves bg-cover bg-opacity-30 bg-green-900 bg-blend-darken">
        <Header />

        {children}
      </body>
    </html>
  );
}
